version: '3.5'

services:
  telegram-download-daemon:
    build: .
    image: telegram-download-daemon:latest
    environment:
      TELEGRAM_DAEMON_API_ID: "${API_ID}"
      TELEGRAM_DAEMON_API_HASH: "${API_HASH}"
      TELEGRAM_DAEMON_CHANNEL: "${DL_CHANNEL_ID}"
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
    volumes:
       - ${TDD_DEST}:/downloads
       - ${TDD_HOME}:/session
    restart: unless-stopped
  